version: '3.0'

services:
  react_frontend:
    build: front-end
    container_name: smol-react
    networks:
      - smol-drops-network
    volumes:
      - react_vol:/var/www/html
    depends_on:
      - express_api_tests

  express_api_tests:
    build: back-end
    container_name: smol-api
    env_file:
      - back-end/.env.test
    ports:
      - 5000:5000
    volumes:
      - psql-db-drops:/var/lib/postgresql/data/
    networks:
      - smol-drops-network
    depends_on:
      - psql_database
  
  psql_database:
    image: postgres:14
    container_name: smol-drops-db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - back-end/.env.test
    volumes:
      - psql-db-drops:/var/lib/postgresql/data/
    networks:
      - smol-drops-network

  nginx:
    build: nginx
    container_name: smol-nginx
    ports:
      - 80:80
    networks:
      - smol-drops-network
    volumes:
      - react_vol:/var/www/html
    depends_on:
      - react_frontend
      - express_api_tests
      - psql_database

volumes:
  react_vol:
  psql-db-drops:

networks:
  smol-drops-network:
    driver: bridge