name: AWS Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create api env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_DB: ${{AWS_postgres.POSTGRES_DB}}
          envkey_POSTGRES_USER: ${{AWS_postgres.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{AWS_postgres.POSTGRES_PASSWORD}}
          envkey_DATABASE_URL: ${{AWS_postgres.DATABASE_URL}}
          directory: back-end/
          fail_on_empty: true
      - name: Create react env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          directory: front-end/
          fail_on_empty: true
      - name: Build docker container
        run: sudo docker-compose build
      - name: Run application
        run: docker-compose down -v && docker-compose up --build -d
